import { StyleSheet } from "react-native";

const colors = {
  primary: '#2E236C',
  secondary: '#83386e',
  accent: '#2196F3',
  backgroundDark: '#17153B',
  buttonBackground: '#ac3a8c',
  borderColor: '#9F2B68',
  textPrimary: '#FFFFFF',
  textSecondary: '#FFB6C1',
  overlay: 'rgba(0, 0, 0, 0.3)',
  overlayLight: 'rgba(0, 0, 0, 0.34)',
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    padding: 20,
  },
  containerContent: {
    marginBottom: 24,
  },
  image: {
    width: '100%',
    height: 240,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginVertical: 16,
  },
  textBox: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 16,
    padding: 16,
    backgroundColor: colors.overlay,
  },
  description: {
    color: colors.textPrimary,
    fontSize: 16,
    textAlign: 'left',
  },
  buttonPrimary: {
    backgroundColor: colors.accent,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 10,
    width: '60%',
    alignSelf: 'center',
  },
  buttonText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  transfer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 20,
  },
  icon: {
    color: colors.textPrimary,
    marginHorizontal: 20,
    marginVertical: 16,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: 300,
    padding: 10,
    backgroundColor: colors.backgroundDark,
    borderRadius: 50,
    marginTop: 10,
    gap: 15,
  },
  containerModal: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: colors.overlayLight,
    paddingTop: 50,
  },
  text: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
    backgroundColor: colors.secondary,
    borderRadius: 8,
    margin: 4,
    padding: 12,
    textAlign: 'center',
  },
  boxModal: {
    width: 360,
    padding: 20,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    color: colors.textSecondary,
    fontSize: 36,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  buttonModal: {
    width: 200,
    height: 50,
    backgroundColor: colors.buttonBackground,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    marginVertical: 8,
  },
  textModal: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  input: {
    textAlign: 'center',
    fontSize: 30,
    color: colors.textPrimary,
  },
  inputModal: {
    width: 300,
    height: 50,
    borderColor: colors.borderColor,
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    color: colors.textPrimary,
    marginBottom: 16,
  },
  labelModal: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  picker: {
    borderWidth: 1,
    borderColor: colors.secondary,
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: colors.overlay,
    color: colors.textPrimary,
    fontSize: 16,
  },
});

export default styles;
